source 'https://rubygems.org'

gem 'eyes_capybara', '~> 3.17'
gem 'capybara', '~> 3.32', '>= 3.32.2'
gem 'rspec', '~> 3.9'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.7'
gem 'webdrivers', '~> 4.3'
#gem 'launchy', '~> 2.5'
gem 'ffi', '~> 1.12', '>= 1.12.2'